[workspace]
resolver = "2"
members = [
    "cgd1-rs",
    "cgd1-rs-cli",
    "cgd1-rs-controller",
    "cgd1-rs-ws",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/smearor/cgd1-rs"

[workspace.dependencies]
async-trait = "0.1"
axum = { version = "0.8", features = ["ws"] }
btleplug = "0.12"
clap = { version = "4", features = ["derive"] }
dirs = "6"
futures = "0.3"
gio = "0.22"
glib = "0.22"
gtk4 = "0.11"
hex = "0.4"
miette = { version = "7", features = ["fancy"] }
rand = "0.10"
rustyline = "18"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
shell-words = "1"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
thiserror = "2"
uuid = { version = "1", features = ["v4"] }
