[book]
title = "cgd1-rs Documentation"
authors = ["Andreas Schaeffer <hanack@nooblounge.net>"]
language = "en"
src = "src"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
git-repository-url = "https://github.com/smearor/cgd1-rs"
additional-js = ["mermaid.min.js", "mermaid-init.js"]
